can name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output_name: codezilla-linux
          - os: macos-latest
            output_name: codezilla-macos
          - os: windows-latest
            output_name: codezilla-windows.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build
        run: |
          go build -o ${{ matrix.output_name }} ./cmd/codezilla

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output_name }}
          path: ${{ matrix.output_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/codezilla-linux/codezilla-linux
            ./artifacts/codezilla-macos/codezilla-macos
            ./artifacts/codezilla-windows.exe/codezilla-windows.exe
          draft: false
          prerelease: false
          generate_release_notes: true